### PR TITLE
Add option to download libil2cpp from the Unity Editor

### PR DESCRIPTION
**Pull request by Kasuromi**

### CODE REVIEW

**Comment by Kasuromi** [comment]
I haven't ran this on all unity versions so it is most likely missing a few paths in older editor versions.

**Comment by ghorsington** [comment]
Thanks! I'll start up dumping locally to see if there are any edge cases (and to actually dump the sources before I upload them).

I'll comment if I find any issues. I'd assume that will start failing on anything older than Unity 5 since I recall Il2Cpp wasn't a thing before that version.

**Comment by Kasuromi** [comment]
[5.2.2f1](https://github.com/Kasuromi/libil2cpp/tree/5.2.2f1) is the first version libil2cpp's source code (that has cpp files) appears

**Comment by ghorsington** [comment]
Fair enough. Maybe in that case the miner should automatically skip trying to extract the libil2cpp for anything lower than that. On a quick look I at least don't see any kind of version check for extracting the source.

**Comment by Kasuromi** [comment]
I wasn't particularly sure if the Linux installers were any different to the MacOS ones as those are the one I used when I made that repository so I didn't add any checks.

Feel free to suggest or commit any changes once you get to a point where it starts failing

**Comment by ghorsington** [comment]
Pushed the necessary changes for supporting all versions. As such, I'll merge this in and then proceed to push all the ZIPs to our database

**Pull request merged**
